use test;


SELECT * FROM QA_BUGLIST;

CREATE TABLE `QA_BUGLIST`(
`BUG_ID` int(4) NOT NULL AUTO_INCREMENT,
`BUG_PROJECT_ID` int,
`BUG_CR_TYPE_ID` int,
`BUG_CR_NUM` VARCHAR(100),
`BUG_TASK_NUM` VARCHAR(100),
`QA_TYPE_ID` int,
`BUG_DESCRIPTION` VARCHAR(2000),
`BUG_RCA` VARCHAR(2000),
`BUG_SOLUTION` VARCHAR(2000),
`QA_ASSIGNEE_ID` int,
`QA_TESTER_ID` int,
`QA_CREATIONDT` datetime,
`QA_UPDATEDT` datetime,
`BUG_DELETED_FLAG` BIT default 0,
`BUG_DELETED_COMMENT` VARCHAR(100),
PRIMARY KEY (`BUG_ID`)
)ENGINE=InnoDB AUTO_INCREMENT=300;

ALTER TABLE `article`
ADD CONSTRAINT `fk_1` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`);

ALTER TABLE `QA_BUGLIST`  ADD  CONSTRAINT `FK_BUG_PROJECT` FOREIGN KEY(`BUG_PROJECT_ID`) REFERENCES `QA_PROJECT` (`PROJECT_ID`);
ALTER TABLE QA_BUGLIST  ADD  CONSTRAINT `FK_BUG_CR_TYPE` FOREIGN KEY(BUG_CR_TYPE_ID) REFERENCES `QA_CRTYPE` (`CR_ID`);
ALTER TABLE QA_BUGLIST  ADD  CONSTRAINT `FK_BUG_QA_TYPE_ID` FOREIGN KEY(QA_TYPE_ID) REFERENCES `QA_RTYPE` (OBJECT_ID);
ALTER TABLE QA_BUGLIST   ADD  CONSTRAINT `FK_BUG_ASSIGN_ID` FOREIGN KEY(`QA_ASSIGNEE_ID`) REFERENCES QA_EMPLOY (EMPLOY_ID);
ALTER TABLE QA_BUGLIST ADD  CONSTRAINT `FK_BUG_qa_ID` FOREIGN KEY(`QA_TESTER_ID`) REFERENCES QA_EMPLOY (EMPLOY_ID);


SELECT * FROM QA_BUGLIST;

INSERT QA_BUGLIST(BUG_PROJECT_ID,BUG_CR_TYPE_ID,BUG_CR_NUM,BUG_TASK_NUM,QA_TYPE_ID,BUG_DESCRIPTION,BUG_RCA,BUG_SOLUTION,QA_ASSIGNEE_ID,QA_TESTER_ID,QA_CREATIONDT,QA_UPDATEDT)
VALUES(3,2,NULL,'',3,'注册接口存在幂等性问题','唯一键','jiejue',1,27,curdate(),curdate());




INSERT QA_PROJECT(PROJECT_NAME,PROJECT_CREATION_DT,PROJECT_UPDATE_DT,PROJECT_DELETED_FLAG)
VALUES('alimama',now(),now(),0)


SELECT * FROM QA_PROJECT;
SELECT * FROM QA_CRTYPE;
SELECT * FROM QA_RTYPE;
SELECT * FROM QA_EMPLOY;


CREATE TABLE `QA_PROJECT` (
`PROJECT_ID` INT NOT NULL AUTO_INCREMENT,
`PROJECT_NAME` VARCHAR(100),
`PROJECT_CREATION_DT` DATE,
`PROJECT_UPDATE_DT` DATE,
`PROJECT_DELETED_FLAG` BIT default 0,
PRIMARY KEY (`PROJECT_ID`)
)ENGINE=InnoDB AUTO_INCREMENT=1;


INSERT QA_CRTYPE(CR_NAME,CR_CREATION_DT,CR_UPDATE_DT) VALUES('内部不收费CR',curdate(),curdate());
INSERT QA_CRTYPE(CR_NAME,CR_CREATION_DT,CR_UPDATE_DT) VALUES('标准收费CR',curdate(),curdate());
INSERT QA_CRTYPE(CR_NAME,CR_CREATION_DT,CR_UPDATE_DT) VALUES('bugFix CR',curdate(),curdate());


CREATE TABLE `QA_CRTYPE` (
`CR_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`CR_NAME` VARCHAR(100),
`CR_CREATION_DT` DATE,
`CR_UPDATE_DT` DATE,
`CR_DELETED_FLAG` BIT default 0)
ENGINE=InnoDB AUTO_INCREMENT=1;





SELECT * FROM QA_EMPLOY;
SELECT * FROM QA_RTYPE;

SET SQL_SAFE_UPDATES = 0;
update QA_EMPLOY set employ_group =2 where EMPLOY_NAME =  '张三';

INSERT into  `QA_EMPLOY`(`EMPLOY_NAME`,`EMPLOY_CREATION_DT`,`EMPLOY_UPDATE_DT`) VALUES('张三',curdate(),curdate());
INSERT into  `QA_EMPLOY`(`EMPLOY_NAME`,`EMPLOY_CREATION_DT`,`EMPLOY_UPDATE_DT`) VALUES('李四',curdate(),curdate());

INSERT QA_RTYPE(OBJECT_NAME,OBJECT_CREATION_DT,OBJECT_UPDATE_DT) VALUES('UAT测试','20181204','20181204') ;
INSERT QA_RTYPE(OBJECT_NAME,OBJECT_CREATION_DT,OBJECT_UPDATE_DT) VALUES('proc测试','20181204','20181204') ;
INSERT QA_RTYPE(OBJECT_NAME,OBJECT_CREATION_DT,OBJECT_UPDATE_DT) VALUES('api测试','20181204','20181204') ;
INSERT QA_RTYPE(OBJECT_NAME,OBJECT_CREATION_DT,OBJECT_UPDATE_DT) VALUES('性能测试','20181204','20181204') ;
INSERT QA_RTYPE(OBJECT_NAME,OBJECT_CREATION_DT,OBJECT_UPDATE_DT) VALUES('ui测试','20181204','20181204') ;
INSERT QA_RTYPE(OBJECT_NAME,OBJECT_CREATION_DT,OBJECT_UPDATE_DT) VALUES('自动化测试','20181204','20181204') ;


CREATE TABLE `QA_RTYPE` (
`OBJECT_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`OBJECT_NAME` VARCHAR(100),
`OBJECT_CREATION_DT` DATE,
`OBJECT_UPDATE_DT` DATE,
`OBJECT_DELETED_FLAG` BIT DEFAULT 0)
ENGINE=InnoDB AUTO_INCREMENT=1;


##DROP TABLE  QA_RTYPE

CREATE TABLE `QA_EMPLOY` (
`EMPLOY_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`EMPLOY_NAME` VARCHAR(100),
`EMPLOY_CREATION_DT` date,
`EMPLOY_UPDATE_DT` date,
`EMPLOY_DELETED_FLAG` BIT default 0)
ENGINE=InnoDB AUTO_INCREMENT=1;


ALTER TABLE QA_EMPLOY ADD EMPLOY_GROUP INT DEFAULT 1;
####增加了一个字段，将测试和开发人员放在同一张表中


SELECT PROJECT_NAME,CR_NAME,BUG_CR_NUM,BUG_TASK_NUM,OBJECT_NAME,BUG_DESCRIPTION
,BUG_RCA,BUG_SOLUTION
###B.EMPLOY_NAME,QA_ASSIGNEE_ID,
###A.EMPLOY_NAME,QA_TESTER_ID
,QA_CREATIONDT,QA_UPDATEDT
FROM QA_BUGLIST
JOIN  QA_PROJECT ON BUG_PROJECT_ID = PROJECT_ID
JOIN  QA_CRTYPE ON CR_ID = BUG_CR_TYPE_ID
JOIN  QA_RTYPE ON OBJECT_ID = QA_TYPE_ID
JOIN QA_EMPLOY A ON A.`EMPLOY_ID` = QA_TESTER_ID AND A.`EMPLOY_GROUP` = 1  ###表示测试
JOIN QA_EMPLOY  B ON B.`EMPLOY_ID` = QA_ASSIGNEE_ID AND B.`EMPLOY_GROUP` = 2   ###表示开发人员
;











