"" 
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[QA_BUGLIST]') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
BEGIN
CREATE TABLE [DBO].QA_BUGLIST (
[BUG_ID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY,
[BUG_PROJECT_ID] int,
[BUG_CR_TYPE_ID] int,
[BUG_CR_NUM] VARCHAR(100),
[BUG_TASK_NUM] VARCHAR(100),
[QA_TYPE_ID] int,
[BUG_DESCRIPTION] VARCHAR(2000),
[BUG_RCA] VARCHAR(2000),
[BUG_SOLUTION] VARCHAR(2000),
[QA_ASSIGNEE_ID] int,
[QA_TESTER_ID] int,
[QA_CREATIONDT] datetime,
[QA_UPDATEDT] datetime,
[BUG_DELETED_FLAG] [BIT] default 0,
[BUG_DELETED_COMMENT] VARCHAR(100)
)
END



ALTER TABLE [DBO].QA_BUGLIST  WITH CHECK ADD  CONSTRAINT [FK_BUG_PROJECT] FOREIGN KEY([BUG_PROJECT_ID])
REFERENCES [DBO].[QA_PROJECT] ([PROJECT_ID])


ALTER TABLE [dbo].QA_BUGLIST CHECK CONSTRAINT [FK_BUG_PROJECT]

ALTER TABLE [DBO].QA_BUGLIST  WITH CHECK ADD  CONSTRAINT [FK_BUG_CR_TYPE] FOREIGN KEY(BUG_CR_TYPE_ID)
REFERENCES [DBO].[QA_CRTYPE] ([CR_ID])

ALTER TABLE [DBO].QA_BUGLIST  WITH CHECK ADD  CONSTRAINT [FK_BUG_QA_TYPE_ID] FOREIGN KEY(QA_TYPE_ID)
REFERENCES [DBO].QA_RTYPE (OBJECT_ID)

ALTER TABLE [DBO].QA_BUGLIST  WITH CHECK ADD  CONSTRAINT [FK_BUG_ASSIGN_ID] FOREIGN KEY([QA_ASSIGNEE_ID])
REFERENCES [DBO].QA_EMPLOY (EMPLOY_ID)

ALTER TABLE [DBO].QA_BUGLIST  WITH CHECK ADD  CONSTRAINT [FK_BUG_qa_ID] FOREIGN KEY([QA_TESTER_ID])
REFERENCES [DBO].QA_EMPLOY (EMPLOY_ID)


SELECT * FROM QA_BUGLIST

INSERT QA_BUGLIST(BUG_PROJECT_ID,BUG_CR_TYPE_ID,BUG_CR_NUM,BUG_TASK_NUM,QA_TYPE_ID,BUG_DESCRIPTION,BUG_RCA,BUG_SOLUTION,QA_ASSIGNEE_ID,QA_TESTER_ID,QA_CREATIONDT,QA_UPDATEDT)
VALUES(6,2,NULL,'',4,'不同批次的文件进行导入，短信SMS内容相同，导致TRACKINGCODE相同','以前未约定过不同天的不同CAMPAIGNID，导入一模一样的短信内容','一个月内短信内容相同的人，保证TRACKINGCODE唯一性',4,1,GETDATE(),GETDATE())



/*
INSERT QA_PROJECT(PROJECT_NAME,PROJECT_CREATION_DT,PROJECT_UPDATE_DT,PROJECT_DELETED_FLAG)
VALUES('联合利华',GETDATE(),GETDATE(),0)


SELECT * FROM QA_PROJECT
SELECT * FROM QA_CRTYPE
SELECT * FROM QA_RTYPE
SELECT * FROM QA_EMPLOY

EMPLOY_ID
1

*/

CREATE TABLE [DBO].QA_PROJECT (
[PROJECT_ID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY,
[PROJECT_NAME] VARCHAR(100),
[PROJECT_CREATION_DT] DATE,
[PROJECT_UPDATE_DT] DATE,
[PROJECT_DELETED_FLAG] [BIT] default 0)

/*
DROP TABLE QA_RTYPE

SELECT * FROM QA_CRTYPE
INSERT QA_CRTYPE(CR_NAME,CR_CREATION_DT,CR_UPDATE_DT)
VALUES('内部不收费CR',GETDATE(),GETDATE())
*/

CREATE TABLE [DBO].QA_CRTYPE (
[CR_ID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY,
[CR_NAME] VARCHAR(100),
[CR_CREATION_DT] DATE,
[CR_UPDATE_DT] DATE,
[CR_DELETED_FLAG] [BIT] default 0)

/*

drop table QA_EMPLOY


DROP TABLE STUDENT

SELECT * FROM QA_EMPLOY

INSERT QA_EMPLOY(EMPLOY_NAME,EMPLOY_CREATION_DT,EMPLOY_UPDATE_DT)
VALUES('LOTUS TAN',GETDATE(),GETDATE())


INSERT QA_RTYPE(OBJECT_NAME,OBJECT_CREATION_DT,OBJECT_UPDATE_DT)
VALUES('UAT测试','20181204','20181204') */

CREATE TABLE [DBO].QA_RTYPE (
[OBJECT_ID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY,
[OBJECT_NAME] VARCHAR(100),
[OBJECT_CREATION_DT] DATE,
[OBJECT_UPDATE_DT] DATE,
[OBJECT_DELETED_FLAG] [BIT] DEFAULT 0)


CREATE TABLE [DBO].QA_EMPLOY (
[EMPLOY_ID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY,
[EMPLOY_NAME] VARCHAR(100),
[EMPLOY_CREATION_DT] date,
[EMPLOY_UPDATE_DT] date,
[EMPLOY_DELETED_FLAG] [BIT] default 0)


ALTER TABLE QA_EMPLOY ADD EMPLOY_GROUP INT DEFAULT 1
--增加了一个字段，将测试和开发人员放在同一张表中

SELECT * FROM QA_EMPLOY

UPDATE QA_EMPLOY SET EMPLOY_GROUP =2 WHERE EMPLOY_ID>=4



SELECT PROJECT_NAME,CR_NAME,BUG_CR_NUM,BUG_TASK_NUM,OBJECT_NAME,BUG_DESCRIPTION
,BUG_RCA,BUG_SOLUTION
--,B.EMPLOY_NAME,QA_ASSIGNEE_ID,
--A.EMPLOY_NAME,QA_TESTER_ID
,QA_CREATIONDT,QA_UPDATEDT
FROM QA_BUGLIST
JOIN  QA_PROJECT ON BUG_PROJECT_ID = PROJECT_ID
JOIN  QA_CRTYPE ON CR_ID = BUG_CR_TYPE_ID
JOIN  QA_RTYPE ON OBJECT_ID = QA_TYPE_ID
JOIN QA_EMPLOY A ON A.[EMPLOY_ID] = QA_TESTER_ID AND A.[EMPLOY_GROUP] = 1  ---表示测试
JOIN QA_EMPLOY  B ON B.[EMPLOY_ID] = QA_ASSIGNEE_ID AND B.[EMPLOY_GROUP] = 2   ---表示开发人员












